In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.6

In [3]:
attendance = np.array([
    7.5, 6.0, 8.2, 5.5, 9.1,
    4.8, 6.8, 8.7, 7.2, 5.9,
    8.0, 9.4, 6.4, 7.8, 8.9,
    5.7, 7.6, 6.9, 9.0, 6.2
])

print(attendance)

[7.5 6.  8.2 5.5 9.1 4.8 6.8 8.7 7.2 5.9 8.  9.4 6.4 7.8 8.9 5.7 7.6 6.9
 9.  6.2]

In [4]:
print("Array:", attendance)
print("Number of dimensions:", attendance.ndim)
print("Shape:", attendance.shape)
print("Size:", attendance.size)
print("Data type:", attendance.dtype)

Array: [7.5 6.  8.2 5.5 9.1 4.8 6.8 8.7 7.2 5.9 8.  9.4 6.4 7.8 8.9 5.7 7.6 6.9
 9.  6.2]
Number of dimensions: 1
Shape: (20,)
Size: 20
Data type: float64

In [5]:
print("Minimum attendance:", np.min(attendance))
print("Maximum attendance:", np.max(attendance))
print("Average attendance:", np.mean(attendance))
print("Total attendance values:", np.sum(attendance))
print("Median attendance:", np.median(attendance))
print("Standard deviation:", np.std(attendance))
print("Variance:", np.var(attendance))

Minimum attendance: 4.8
Maximum attendance: 9.4
Average attendance: 7.279999999999999
Total attendance values: 145.6
Median attendance: 7.35
Standard deviation: 1.320454467219525
Variance: 1.7435999999999996

In [6]:
print("Sorted attendance:", np.sort(attendance))
print("First value:", attendance[0])
print("Last value:", attendance[-1])
print("First five values:", attendance[:5])
print("Attendance above 8:", attendance[attendance > 8])

Sorted attendance: [4.8 5.5 5.7 5.9 6.  6.2 6.4 6.8 6.9 7.2 7.5 7.6 7.8 8.  8.2 8.7 8.9 9.
 9.1 9.4]
First value: 7.5
Last value: 6.2
First five values: [7.5 6.  8.2 5.5 9.1]
Attendance above 8: [8.2 9.1 8.7 9.4 8.9 9. ]

In [7]:
print("Add 1 to every value:", attendance + 1)
print("Subtract 1:", attendance - 1)
print("Multiply by 2:", attendance * 2)
print("Divide by 2:", attendance / 2)

Add 1 to every value: [ 8.5  7.   9.2  6.5 10.1  5.8  7.8  9.7  8.2  6.9  9.  10.4  7.4  8.8
  9.9  6.7  8.6  7.9 10.   7.2]
Subtract 1: [6.5 5.  7.2 4.5 8.1 3.8 5.8 7.7 6.2 4.9 7.  8.4 5.4 6.8 7.9 4.7 6.6 5.9
 8.  5.2]
Multiply by 2: [15.  12.  16.4 11.  18.2  9.6 13.6 17.4 14.4 11.8 16.  18.8 12.8 15.6
 17.8 11.4 15.2 13.8 18.  12.4]
Divide by 2: [3.75 3.   4.1  2.75 4.55 2.4  3.4  4.35 3.6  2.95 4.   4.7  3.2  3.9
 4.45 2.85 3.8  3.45 4.5  3.1 ]

In [8]:
categories = np.where(attendance >= 8, "High", "Low")

print(categories)
print("High attendance count:", np.sum(attendance >= 8))
print("Low attendance count:", np.sum(attendance < 8))

['Low' 'Low' 'High' 'Low' 'High' 'Low' 'Low' 'High' 'Low' 'Low' 'High'
 'High' 'Low' 'Low' 'High' 'Low' 'Low' 'Low' 'High' 'Low']
High attendance count: 7
Low attendance count: 13

In [9]:
import pandas as pd

df = pd.read_csv("student_performance_dataset_20_rows.csv")

df

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance
0,1,18,Female,Student,7.5,Good
1,2,21,Male,Student,6.0,Average
2,3,19,Female,Student,8.2,Good
3,4,22,Male,Part-time,5.5,Average
4,5,20,Female,Student,9.1,Excellent
5,6,23,Male,Full-time,4.8,Needs Improvement
6,7,18,Male,Student,6.8,Average
7,8,21,Female,Part-time,8.7,Excellent
8,9,20,Male,Student,7.2,Good
9,10,24,Female,Full-time,5.9,Average
10,11,19,Male,Student,8.0,Good
11,12,22,Female,Student,9.4,Excellent
12,13,20,Female,Part-time,6.4,Average
13,14,23,Male,Full-time,7.8,Good
14,15,18,Female,Student,8.9,Excellent
15,16,21,Male,Student,5.7,Average
16,17,19,Female,Student,7.6,Good
17,18,22,Male,Part-time,6.9,Average
18,19,20,Female,Student,9.0,Excellent
19,20,24,Male,Full-time,6.2,Average

In [10]:
df.head()

   Student_ID  Age  Gender Study_Status  Attendance_Percent Performance
0           1   18  Female      Student                 7.5        Good
1           2   21    Male      Student                 6.0     Average
2           3   19  Female      Student                 8.2        Good
3           4   22    Male    Part-time                 5.5     Average
4           5   20  Female      Student                 9.1   Excellent

In [11]:
df.head(10)

   Student_ID  Age  Gender Study_Status  Attendance_Percent        Performance
0           1   18  Female      Student                 7.5               Good
1           2   21    Male      Student                 6.0            Average
2           3   19  Female      Student                 8.2               Good
3           4   22    Male    Part-time                 5.5            Average
4           5   20  Female      Student                 9.1          Excellent
5           6   23    Male    Full-time                 4.8  Needs Improvement
6           7   18    Male      Student                 6.8            Average
7           8   21  Female    Part-time                 8.7          Excellent
8           9   20    Male      Student                 7.2               Good
9          10   24  Female    Full-time                 5.9            Average

In [12]:
df.tail()

    Student_ID  Age  Gender Study_Status  Attendance_Percent Performance
15          16   21    Male      Student                 5.7     Average
16          17   19  Female      Student                 7.6        Good
17          18   22    Male    Part-time                 6.9     Average
18          19   20  Female      Student                 9.0   Excellent
19          20   24    Male    Full-time                 6.2     Average

In [13]:
df.tail(3)

    Student_ID  Age  Gender Study_Status  Attendance_Percent Performance
17          18   22    Male    Part-time                 6.9     Average
18          19   20  Female      Student                 9.0   Excellent
19          20   24    Male    Full-time                 6.2     Average

In [14]:
print("Shape:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Shape: (20, 6)
Number of rows: 20
Number of columns: 6

In [15]:
print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Study_Status', 'Attendance_Percent',
       'Performance'],
      dtype='str')

In [16]:
print(df.columns.tolist())

['Student_ID', 'Age', 'Gender', 'Study_Status', 'Attendance_Percent', 'Performance']

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          20 non-null     int64
 1   Age                 20 non-null     int64
 2   Gender              20 non-null     str
 3   Study_Status        20 non-null     str
 4   Attendance_Percent  20 non-null     float64
 5   Performance         20 non-null     str
dtypes: float64(1), int64(2), str(3)
memory usage: 1.1 KB

In [18]:
df.dtypes

Student_ID              int64
Age                     int64
Gender                    str
Study_Status              str
Attendance_Percent    float64
Performance               str
dtype: object

In [19]:
df.shape

(20, 6)

In [20]:
df.describe()

       Student_ID       Age  Attendance_Percent
count    20.00000  20.00000           20.000000
mean     10.50000  20.70000            7.280000
std       5.91608   1.92217            1.354758
min       1.00000  18.00000            4.800000
25%       5.75000  19.00000            6.150000
50%      10.50000  20.50000            7.350000
75%      15.25000  22.00000            8.325000
max      20.00000  24.00000            9.400000

In [21]:
df.describe(include="all")

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance
count,20.00000,20.00000,20,20,20.000000,20
unique,NaN,NaN,2,3,NaN,4
top,NaN,NaN,Female,Student,NaN,Average
freq,NaN,NaN,10,12,NaN,8
mean,10.50000,20.70000,NaN,NaN,7.280000,NaN
std,5.91608,1.92217,NaN,NaN,1.354758,NaN
min,1.00000,18.00000,NaN,NaN,4.800000,NaN
25%,5.75000,19.00000,NaN,NaN,6.150000,NaN
50%,10.50000,20.50000,NaN,NaN,7.350000,NaN
75%,15.25000,22.00000,NaN,NaN,8.325000,NaN
max,20.00000,24.00000,NaN,NaN,9.400000,NaN

In [22]:
print("Mean:", df["Attendance_Percent"].mean())
print("Median:", df["Attendance_Percent"].median())
print("Minimum:", df["Attendance_Percent"].min())
print("Maximum:", df["Attendance_Percent"].max())
print("Sum:", df["Attendance_Percent"].sum())
print("Standard deviation:", df["Attendance_Percent"].std())

Mean: 7.279999999999999
Median: 7.35
Minimum: 4.8
Maximum: 9.4
Sum: 145.6
Standard deviation: 1.3547576982813683

In [23]:
df.isnull()

    Student_ID    Age  Gender  Study_Status  Attendance_Percent  Performance
0        False  False   False         False               False        False
1        False  False   False         False               False        False
2        False  False   False         False               False        False
3        False  False   False         False               False        False
4        False  False   False         False               False        False
5        False  False   False         False               False        False
6        False  False   False         False               False        False
7        False  False   False         False               False        False
8        False  False   False         False               False        False
9        False  False   False         False               False        False
10       False  False   False         False               False        False
11       False  False   False         False               False        False
12       False  False   False         False               False        False
13       False  False   False         False               False        False
14       False  False   False         False               False        False
15       False  False   False         False               False        False
16       False  False   False         False               False        False
17       False  False   False         False               False        False
18       False  False   False         False               False        False
19       False  False   False         False               False        False

In [24]:
df.isnull().sum()

Student_ID            0
Age                   0
Gender                0
Study_Status          0
Attendance_Percent    0
Performance           0
dtype: int64

In [25]:
df.isnull().sum().sum()

np.int64(0)

In [26]:
df.isnull().mean() * 100

Student_ID            0.0
Age                   0.0
Gender                0.0
Study_Status          0.0
Attendance_Percent    0.0
Performance           0.0
dtype: float64

In [27]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df[df.duplicated()]

Empty DataFrame
Columns: [Student_ID, Age, Gender, Study_Status, Attendance_Percent, Performance]
Index: []

In [30]:
df["Attendance_Status"] = df["Attendance_Percent"].apply(
    lambda x: "High" if x >= 8 else "Low"
)

df.head()

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance,Attendance_Status
0,1,18,Female,Student,7.5,Good,Low
1,2,21,Male,Student,6.0,Average,Low
2,3,19,Female,Student,8.2,Good,High
3,4,22,Male,Part-time,5.5,Average,Low
4,5,20,Female,Student,9.1,Excellent,High

In [31]:
df["Age_Group"] = df["Age"].apply(
    lambda x: "Young" if x <= 20 else "Older"
)

df.head()

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance,Attendance_Status,Age_Group
0,1,18,Female,Student,7.5,Good,Low,Young
1,2,21,Male,Student,6.0,Average,Low,Older
2,3,19,Female,Student,8.2,Good,High,Young
3,4,22,Male,Part-time,5.5,Average,Low,Older
4,5,20,Female,Student,9.1,Excellent,High,Young

In [32]:
df["Attendance_Score_100"] = df["Attendance_Percent"] * 10

df.head()

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance,Attendance_Status,Age_Group,Attendance_Score_100
0,1,18,Female,Student,7.5,Good,Low,Young,75.0
1,2,21,Male,Student,6.0,Average,Low,Older,60.0
2,3,19,Female,Student,8.2,Good,High,Young,82.0
3,4,22,Male,Part-time,5.5,Average,Low,Older,55.0
4,5,20,Female,Student,9.1,Excellent,High,Young,91.0

In [33]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Study_Status', 'Attendance_Percent',
       'Performance', 'Attendance_Status', 'Age_Group',
       'Attendance_Score_100'],
      dtype='str')

In [34]:
df["Age"].mean()

np.float64(20.7)

In [35]:
df["Attendance_Percent"].mean()

np.float64(7.279999999999999)

In [36]:
print("Minimum age:", df["Age"].min())
print("Maximum age:", df["Age"].max())

Minimum age: 18
Maximum age: 24

In [37]:
df["Attendance_Percent"].sum()

np.float64(145.6)

In [38]:
df["Student_ID"].count()

np.int64(20)

In [39]:
df.select_dtypes(include="number").agg(
    ["count", "mean", "min", "max", "sum"]
)

       Student_ID    Age  Attendance_Percent  Attendance_Score_100
count        20.0   20.0               20.00                  20.0
mean         10.5   20.7                7.28                  72.8
min           1.0   18.0                4.80                  48.0
max          20.0   24.0                9.40                  94.0
sum         210.0  414.0              145.60                1456.0

In [40]:
df["Performance"].value_counts()

Performance
Average              8
Good                 6
Excellent            5
Needs Improvement    1
Name: count, dtype: int64

In [41]:
df["Performance"].value_counts()

Performance
Average              8
Good                 6
Excellent            5
Needs Improvement    1
Name: count, dtype: int64

In [42]:
df.groupby("Performance")["Attendance_Percent"].mean()

Performance
Average              6.175000
Excellent            9.020000
Good                 7.716667
Needs Improvement    4.800000
Name: Attendance_Percent, dtype: float64

In [43]:
df["Study_Status"].value_counts()

Study_Status
Student      12
Part-time     4
Full-time     4
Name: count, dtype: int64

In [44]:
df.groupby("Study_Status")["Attendance_Percent"].mean()

Study_Status
Full-time    6.175000
Part-time    6.875000
Student      7.783333
Name: Attendance_Percent, dtype: float64

In [45]:
pd.crosstab(df["Study_Status"], df["Performance"])

Performance   Average  Excellent  Good  Needs Improvement
Study_Status
Full-time           2          0     1                  1
Part-time           3          1     0                  0
Student             3          4     5                  0

In [46]:
df[df["Attendance_Percent"] > 8]

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance,Attendance_Status,Age_Group,Attendance_Score_100
2,3,19,Female,Student,8.2,Good,High,Young,82.0
4,5,20,Female,Student,9.1,Excellent,High,Young,91.0
7,8,21,Female,Part-time,8.7,Excellent,High,Older,87.0
11,12,22,Female,Student,9.4,Excellent,High,Older,94.0
14,15,18,Female,Student,8.9,Excellent,High,Young,89.0
18,19,20,Female,Student,9.0,Excellent,High,Young,90.0

In [47]:
df[df["Age"] < 20]

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance,Attendance_Status,Age_Group,Attendance_Score_100
0,1,18,Female,Student,7.5,Good,Low,Young,75.0
2,3,19,Female,Student,8.2,Good,High,Young,82.0
6,7,18,Male,Student,6.8,Average,Low,Young,68.0
10,11,19,Male,Student,8.0,Good,High,Young,80.0
14,15,18,Female,Student,8.9,Excellent,High,Young,89.0
16,17,19,Female,Student,7.6,Good,Low,Young,76.0

In [48]:
df[df["Performance"] == "Excellent"]

,Student_ID,Age,Gender,Study_Status,Attendance_Percent,Performance,Attendance_Status,Age_Group,Attendance_Score_100
4,5,20,Female,Student,9.1,Excellent,High,Young,91.0
7,8,21,Female,Part-time,8.7,Excellent,High,Older,87.0
11,12,22,Female,Student,9.4,Excellent,High,Older,94.0
14,15,18,Female,Student,8.9,Excellent,High,Young,89.0
18,19,20,Female,Student,9.0,Excellent,High,Young,90.0